import {
  AcUnitOutlined as ACIcon,
  LocalParkingOutlined as LocalParkingIcon,
  SportsEsportsOutlined as SportsEsportsIcon,
  GrassOutlined as GrassIcon,
  PoolOutlined as PoolIcon,
  TvOutlined as TvIcon,
  OpacityOutlined as OpacityIcon,
  WifiOutlined as WifiIcon,
  WineBar as BarCounter,
  PlumbingOutlined as EVCharging,
  LocalFireDepartmentOutlined as Bonfire,
  ChairOutlined as Sitoutarea,
  DeckOutlined as Gazebo,
  RestaurantMenuOutlined as Restaurant,
  ShowerOutlined as Raindance,
  BathtubOutlined as Bathtub,
  SportsCricketOutlined as Turf,
  WorkspacesOutlined as Workspace,
  FitnessCenterOutlined as Gym,
  ThermostatOutlined as TempControlPool,
  HotTubOutlined as Hottub,
  OutdoorGrillOutlined as BBQGrill,
} from "@mui/icons-material";
import BarTender from "./custom-icons/BarTender";

const amenityIconMap: Record<string, React.ElementType> = {
  airconditioned: ACIcon,
  freeparking: LocalParkingIcon,
  indoorgames: SportsEsportsIcon,
  lawn: GrassIcon,
  swimmingpool: PoolIcon,
  television: TvIcon,
  watersupply: OpacityIcon,
  wifi: WifiIcon,
  barCounter: BarCounter,
  barTender: BarTender,
  evcharging: EVCharging,
  bonfire: Bonfire,
  restaurant: Restaurant,
  sitoutarea: Sitoutarea,
  gazebo: Gazebo,
  raindance: Raindance,
  bathtub: Bathtub,
  turf: Turf,
  gym: Gym,
  workspace: Workspace,
  tempControlPool: TempControlPool,
  openDinning: Gazebo,
  hottub: Hottub,
  bbqgrill: BBQGrill,
};

export default amenityIconMap;
